import type { Metadata } from "next";
import "./globals.css";
import { Figtree } from 'next/font/google'


const figtree = Figtree({
  subsets: [ 'latin' ],
  fallback: [
    '-apple-system',
    'BlinkMacSystemFont',
    'avenir next',
    'avenir',
    'segoe ui',
    'helvetica neue',
    'helvetica',
    'Cantarell',
    'Ubuntu',
    'roboto',
    'noto',
    'arial',
    'sans-serif'
  ]
})

export const metadata: Metadata = {
  title: "3D print price calculator",
  description: "Generated by phasio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={figtree.className}
      >
        {children}
      </body>
    </html>
  );
}
